global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus self monitoring
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Sentinel Gate API Gateway
  - job_name: "sentinel-gate"
    static_configs:
      - targets: ["gateway:8080"]
    metrics_path: "/metrics"
    scrape_interval: 5s
    scrape_timeout: 5s

  # Mock services monitoring (if they have metrics endpoints)
  - job_name: "user-service"
    static_configs:
      - targets: ["user-service:1080"]
    metrics_path: "/metrics"
    scrape_interval: 10s

  - job_name: "order-service"
    static_configs:
      - targets: ["order-service:1080"]
    metrics_path: "/metrics"
    scrape_interval: 10s

  # Redis exporter (if we add one later)
  # - job_name: 'redis'
  #   static_configs:
  #     - targets: ['redis-exporter:9121']
