apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1
  - name: Jaeger
    orgId: 1

datasources:
  # Prometheus datasource for metrics
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    basicAuth: false
    isDefault: true
    version: 1
    editable: true
    jsonData:
      httpMethod: POST
      manageAlerts: true
      prometheusType: Prometheus
      prometheusVersion: 2.40.0
      cacheLevel: "High"
      disableRecordingRules: false
      incrementalQueryOverlapWindow: 10m
      exemplarTraceIdDestinations:
        - name: traceID
          datasourceUid: jaeger

  # Jaeger datasource for tracing
  - name: Jaeger
    type: jaeger
    access: proxy
    orgId: 1
    uid: jaeger
    url: http://jaeger:16686
    basicAuth: false
    isDefault: false
    version: 1
    editable: true
    jsonData:
      tracesToLogsV2:
        datasourceUid: "loki"
        spanStartTimeShift: "-1h"
        spanEndTimeShift: "1h"
        tags: ["job", "instance", "pod", "namespace"]
        filterByTraceID: false
        filterBySpanID: false
        customQuery: true
        query: "sum(rate(tempo_spanmetrics_latency_bucket{$$__tags}[$$__interval])) by (le)"
      tracesToMetrics:
        datasourceUid: "prometheus"
        spanStartTimeShift: "-1h"
        spanEndTimeShift: "1h"
        tags:
          [
            { key: "service.name", value: "service" },
            { key: "service.namespace", value: "namespace" },
          ]
        queries:
          - name: "Sample query"
            query: "sum(rate(http_requests_total{$$__tags}[$$__interval]))"
      nodeGraph:
        enabled: true
      search:
        hide: false
      spanBar:
        type: "Tag"
        tag: "http.path"
